### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
Taking into account the notes in: https://github.com/usegalaxy-eu/pulsar-deployment/issues/7

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
xref: https://github.com/usegalaxy-eu/pulsar-deployment/pull/8

**Comment by sebastian-luna-valero** [comment]
sorry, seeing https://github.com/usegalaxy-eu/pulsar-deployment/pull/9 just now so please fill free to close without merging

**Comment by bgruening** [comment]
I merged 9, maybe you can rebase your PR or add anything that is still missing in a new PR?

Thanks @sebastian-luna-valero

**Comment by sebastian-luna-valero** [comment]
Thanks, I just did minor changes.

**Review by bgruening — APPROVED** [review]
Great. Thanks a lot @sebastian-luna-valero

**Comment by bgruening** [comment]
Please do not forget to register for the workshop :)

**Pull request merged**
